services:
  db:
    image: postgres:13
    container_name: bucketlist-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: bucketlist
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    container_name: bucketlist-redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: bucketlist-backend
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bucketlist
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_REDIS_HOST: redis 
      MAIL_EMAIL: ${MAIL_EMAIL}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      UPLOAD_PATH: file:./uploads/
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: bucketlist-frontend
    env_file:
      - .env
    ports:
      - "5173:5173"
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data: 