spring:
  application:
    name: bucketlist

  datasource:
    url: jdbc:postgresql://localhost:5432/bucketlist
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379

  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  web:
    resources:
      static-locations: ${UPLOAD_PATH:file}

  # SMTP
  mail:
    host: smtp.naver.com
    port: 465
    username: ${MAIL_EMAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
    default-encoding: UTF-8

jwt:
  secret-key: ${JWT_SECRET_KEY}